Repository One-Degree-North/mate-rnd-oqbot, pull requests merged in 2021-07, with the labels that each got.

#27 Improved controls 2
  .gitignore
  comms.py
  controls_pyqt/gui.py
  controls_pyqt/key_signal.py
  imu_compensator.py
  utils.py
Labels: communications, controls, enhancement, important

#29 Added new layout to compare coral
  controls_pyqt/coral.png
  controls_pyqt/gui.py
Labels: Qt, enhancement

#30 Fixed Alignment on labels
  controls_pyqt/gui.py
Labels: Qt
