Repository One-Degree-North/mate-rnd-oqbot, pull requests merged in 2021-06, with the labels that each got.

#4 Add MCU and MCU Interfacing
  .gitignore
  docs/mcu_cli.md
  mcu-code/mcu-code.ino
  mcu-lib/command_constants.py
  mcu-lib/mcu.py
  mcu-lib/mcu_cli.py
  mcu-lib/packets.py
  mcu-tests/multi-sensor-test/multi-sensor-test.ino
  mcu-tests/multi-serial-test/multi-serial-test.ino
  mcu-tests/pwm-test/pwm-test.ino
Labels: important

#3 Controls
  controls-pygame/controls.py
  controls-pygame/exit_program.py
Labels: enhancement

#6 Qt controls gui combined
  .gitignore
  controls-pyqt/exit_program.py
  controls-pyqt/gui.py
Labels: enhancement

#8 Fixed numerous glitches
  controls-pyqt/gui.py
Labels: bug

#5 Comms
  comms.py
Labels: enhancement

#20 Added the abiliy to save photos
  controls_pyqt/gui.py
Labels: enhancement

#23 implement BNO055 and two extra sensor channels
  comms.py
  controls_pyqt/gui.py
  docs/command-list.md
  docs/mcu_cli.md
  mcu-code/mcu-code.ino
  mcu_cli.py
  mcu_lib/command_constants.py
  mcu_lib/mcu.py
  mcu_lib/packets.py
Labels: MCU lib, enhancement, important

#25 Camera Enhancements
  controls_pyqt/gui.py
Labels: Qt, enhancement

#26 Added option to disable sidebar
  controls_pyqt/gui.py
Labels: Qt, enhancement
